
## deepSeek?????
ai.model.deepseek.modelId=deepseek-v4-pro
ai.model.deepseek.apiKey=sk-65ecfffa33b7467f8ee5a76d01eaf574
ai.model.deepseek.name=deepseek
ai.model.deepseek.service=deepseek
ai.model.deepseek.modelName:deepseek-v4-pro
ai.model.baseUrl=https://signin.aliyun.com/1686046264250341.onaliyun.com/login.htm
